# Generated by Django 4.2.6 on 2023-10-16 20:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Additional_Costs",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("description", models.CharField(max_length=100)),
                ("price", models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name="Base_Coverage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("base_coverage_type", models.CharField(max_length=100)),
                ("price", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("state", models.CharField(max_length=50)),
                ("tax_multiplier", models.FloatField(default=1.0)),
                ("flood_multiplier", models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("pet", models.BooleanField(default=False)),
                ("flood_coverage", models.BooleanField(default=False)),
                ("subtotal", models.FloatField()),
                ("taxes", models.FloatField()),
                ("total_price", models.FloatField()),
                (
                    "additional_costs",
                    models.ManyToManyField(to="home.additional_costs"),
                ),
                (
                    "coverage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coverage_obj",
                        to="home.base_coverage",
                    ),
                ),
                (
                    "coverage_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coverage_state_obj",
                        to="home.state",
                    ),
                ),
            ],
        ),
    ]
