# Generated by Django 4.2.6 on 2023-10-16 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='flood_coverage',
            new_name='has_flood_coverage',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='pet',
            new_name='has_pet',
        ),
    ]
