# Generated by Django 4.2.6 on 2023-10-17 00:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_flood_coverage_quote_has_flood_coverage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='id',
            field=models.UUIDField(default=uuid.UUID('71de836c-91c9-4812-8279-43f2b387877e'), primary_key=True, serialize=False),
        ),
    ]
