# Generated by Django 4.2.6 on 2023-10-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_alter_quote_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="quote",
            name="taxes",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="quote",
            name="total_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
