# Generated by Django 4.2.6 on 2023-10-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_quote_id_alter_quote_subtotal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
