# Generated by Django 4.2.6 on 2023-10-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_additional_costs_id_alter_base_coverage_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_coverage',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='state',
            name='flood_multiplier',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='state',
            name='tax_multiplier',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
