# Generated by Django 4.2.6 on 2023-10-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_base_coverage_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additional_costs',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
